import { City } from "@/Types/City";

export const albany: City = {
  cityName: 'Albany',
  dateOfAdmission: '1686',
  cityPopulation: 97856,
  cityRegion: 'Capital District',
  cityClassification: 'Capital',
  averageIncome: 28612,
  mainBody: 'Albany, city, capital (1797) of the state of New York, U.S., and seat (1683) of Albany county. It lies along the Hudson River, 143 miles (230 km) north of New York City. The heart of a metropolitan area that includes Troy and Schenectady, it is a port city, the northern terminus of the deepwater Hudson River Channel, and a natural transshipment point between oceangoing vessels and the New York State Canal System routes to the Great Lakes.',
  mainBody2: 'In 1609 the English explorer Henry Hudson anchored the Half-Moon in the shallows near the site while searching for the Northwest Passage. Fort Nassau, built in 1614 on Castle Island (now part of the Port of Albany), became a trading post for the New Netherland Company. A group of Walloon families built Fort Orange near the site in 1624 and began the first permanent settlement, known as Beverwyck. In 1629 the Dutch West India Company granted tracts along both sides of the river (including Beverwyck) to Kiliaen van Rensselaer, an Amsterdam merchant. Renamed Rensselaerswyck, the area attracted a sizable number of colonists, and in 1652 Peter Stuyvesant, colonial governor for the Dutch West India Company, obtained independent status for the village of Beverwyck from the van Rensselaer family. When Fort Orange surrendered to the British (September 24, 1664), the village was renamed to honour James, duke of York and Albany (later King James II). It was granted a city charter by the British governor Thomas Dongan on July 22, 1686. Albany’s strategic location and the construction of Fort Frederick made it a leading colonial city. Its population of 2,273 in 1703 increased to 3,498 in 1790 (the year of the first U.S. census) and to 50,763 by 1850. The Dutch heritage is reflected in many street names and in the annual Tulip Festival held in May in Washington Park.',
  mainBody3: 'In 1689 one of the first intercolonial conventions was held at Albany to discuss a system of mutual defense. A more significant historical gathering was the Albany Congress, which took place in 1754. This meeting paved the way for the Congress of 1765 and the Continental Congress of 1774. Migrating pioneers began to appear in Albany as early as 1783, and the city, a thriving fur-trading centre, became a major outfitting point for wagon trains going west. The opening of the Erie Canal (1825) and the advent of the railroad (1831) increased the flow of traffic through the city, which became the hub of transportation to Michigan Territory (the upper Great Lakes).',
};